version: "2"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
    - ENV_BASE_URL="http://localhost"
    restart: always
    ports:
    - "8000:8000"
    tty: true