version: "2"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
    - ENV_BASE_URL=http://localhost:8000/
    restart: always
    ports:
    - "8000:8000"
    tty: true